### PR TITLE
no need of sudo to pip install crcmod on macOS

### PR DESCRIPTION
**Pull request by Nakilon**
It works without `sudo`. Did it 10 minutes ago.

### CODE REVIEW

**Comment by dilipped** [comment]
Thanks for the PR. You might have the correct permissions or you must be using the python installed for your user and hence sudo was not required. Still majority of cases are those that required sudo so I think the documentation in its current state makes sense for majority of cases and I don't think it's worth changing the instructions just for macOS.

**Comment by Nakilon** [comment]
That documentation line is already in the macOS specific chapter.
Also macOS is not like a docker container or some messy temporary linux installation. It is a bad practice to run things with sudo on macOS.

**Comment by dilipped** [comment]
I see. Thanks for the explanation.

**Comment by Nakilon** [comment]
Thank you!

**Pull request merged**
