### PR TITLE
Remove boto from git submodules.

### PR DESCRIPTION
**Pull request by houglum**
Following the instructions from https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule, because this was way harder than it should have been :upside_down_face: 

This is a follow-up to #645.

### CODE REVIEW

**Comment by catleeball** [comment]
Oh wait, I see travis failed to build boto:

```
xception: Unable to find required boto test source file at /tmp/pip-YA6XcB-build/third_party/boto/tests/integration/s3/mock_storage_service.py or /tmp/pip-YA6XcB-build/gslib/tests/mock_storage_service.py.
```

We might need to update `setup.py` too maybe

**Comment by catleeball** [comment]
Looks like line 169: `packages=find_packages(exclude=['third_party']),` we could add the vendored subdir and maybe that will satisfy travis running `pip install .`

**Comment by catleeball** [comment]
Also possible culprits in setup.py:

https://github.com/GoogleCloudPlatform/gsutil/blob/6376292583d48bc19d19ae8caf47c862a5f07cd5/setup.py#L68

`BOTO_DIR = os.path.join(CURDIR, 'third_party', 'boto'`

and dependency links on line 59:
```
dependency_links = [
    # Note: this commit ID should be kept in sync with the 'third_party/boto'
    # entry in 'git submodule status'.
    # pylint: disable=line-too-long
    'https://github.com/boto/boto/archive/8fac1878734c5ac085b781f619c70ea4b6e913c3.tar.gz#egg=boto-2.49.0',
    # pylint: enable=line-too-long
]
```

**Comment by houglum** [comment]
Was in a hurry to do this before leaving earlier and completely forgot to also update setup.py. Whoops. This is why we have presubmits :upside_down_face: 

After commit e21ad3c, I manually ran `pip install .` in a new virtualenv while in the root of my local repository, and all was well with the world.  Travis also seems to be happy again, PTAL.

**Pull request merged**
