### PR TITLE
Replace socks library

### PR DESCRIPTION
**Pull request by dilipped**
b/161686363: Proxy authentication does not work on Python3 because of socksipy-branch lib. Replacing it with pysocks.

### CODE REVIEW

**Comment by NickGoog** [comment]
Do we need to do any due diligence on this package before accepting it into the codebase?

**Comment by dilipped** [comment]
@NickGoog I have seen the package being used internally for other stuff so I think we should be good. But that's a good point and being extra careful doesn't hurt. I will try to compare if the stuff in third_party has some modification or if it being used as it is.

**Comment by dilipped** [comment]
Looks like kokoro tests are failing for windows. 
```
ImportError: To run PySocks on Windows you must install win_inet_pton
```
I will look into this.

**Comment by dilipped** [comment]
I have a better way of addressing this problem and I think this change will no longer be needed. I will close this PR once I confirm the alternate solution works.

**Comment by thomasmaclean** [comment]
What's the alternative solution?

**Comment by dilipped** [comment]
@thomasmaclean  Remove socksipy, but do not replace it with PySocks. Instead rely on the `socks.py` module present in httplib2 https://github.com/httplib2/httplib2/blob/master/python3/httplib2/socks.py

**Comment by dilipped** [comment]
Closing this PR in favor of https://github.com/GoogleCloudPlatform/gsutil/pull/1084 which provides a better alternative to this problem and does not require additional dependency for Windows.

**Pull request closed without merging**
