### PR TITLE
Fix SSL missing error by updating Linux Python 3.5 version.

### PR DESCRIPTION
**Pull request by NickGoog**
See https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install

### CODE REVIEW

**Comment by NickGoog** [comment]
The Python 3.5 tests are running, but seem to have more errors than the other Python version tests (`WeakValueDictionary`). Since 3.5 is being deprecated soon'ish. The failure is likely this Python bug in 3.5.3: https://bugs.python.org/issue29519

Switching to 3.5.4 to see if it helps as suggested here (didn't actually see evidence in the link in the post but will test): https://github.com/ansible/ansible/issues/21982#issuecomment-424303758

**Comment by NickGoog** [comment]
Python 3.5.4 solved the `WeakValueDictionary` issue

**Comment by dilipped** [comment]
All linux tests seem to be failing. Especially something like 
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 21118: invalid start byte
```
Has this started happening after the pool change? Can you try doing https://github.com/GoogleCloudPlatform/gsutil/blob/09257c0e83df44641d56ba3c3b1fc806d541a413/test/ci/kokoro/run_integ_tests.sh#L41 for linux as well?

**Comment by NickGoog** [comment]
```
if [[ $KOKORO_JOB_NAME =~ "macos" || $KOKORO_JOB_NAME =~ "linux" ]]; then
  export LANG=en_US.UTF-8
fi
```
Didn't seem to work (not posting logs externally).

I also tried:
```
if [[ $KOKORO_JOB_NAME =~ "macos" || $KOKORO_JOB_NAME =~ "linux" ]]; then
  export LANG=en_US.UTF-8
  export PYTHONIOENCODING=utf-8
fi
```

The ASCII error appears on Linux on Python 3.5 and 3.6 (not 3.7 and 3.8).

Playing around with some other env vars

**Comment by NickGoog** [comment]
@dilipped , I set different env vars for Linux, and it's looking good!

**Comment by dilipped** [comment]
> @dilipped , I set different env vars for Linux, and it's looking good!

Nice! Good job fixing the utf-8 issue. Looks like all tests are still failing for unrelated changes. Do we have a fix for it or can this be assigned to the current on-duty?

**Review by dilipped — APPROVED** [review]

**Comment by NickGoog** [comment]
@dilipped , yeah, the failures related to POSIX and unwritable files have been happening so consistently I don't think they're flakes. Did not investigate a fix, but I'm going to do some light research into all the current bugs for https://github.com/GoogleCloudPlatform/gsutil/pull/1689

**Comment by NickGoog** [comment]
The Windows Kokoro VM is now broken, seemingly as a result of an internal CL changing the VM platform. Handing off to the next OnDuty @rrauber

**Pull request merged**
