### PR TITLE
deps: Pin pyopenssl dependency (==24.2.1)

### LINKED ISSUE #1820: gsutil broken by upgrade to pyopenssl (24.3)
pyopenssl has removed a load of libs and this now breaks gsutil (importing `crypto` from pyopenssl)

probably the dep here needs to be pinned pending an update to the code

### PR DESCRIPTION
**Pull request by phlax**
Workaround/fix #1820

### CODE REVIEW

**Comment by phlax** [comment]
testing this elsewhere it seems that its necessary to hard pin this

**Comment by jayhatha** [comment]
@sushantkhanna @sameer-google

**Comment by ArisBee** [comment]
Hello all,

This issue is causing significant disruptions. Could this fix be merged and pushed to production as soon as possible?

Thank you!

**Comment by sameer-google** [comment]
this issue has been fixed in gsutil release 5.32, please upgrade gsutil to latest version available.

**Comment by sameer-google** [comment]
Alpine images is rolled back to version `3.19` in `504.0.0-alpine`. So the issue with `OpenSSL.crypto` should be resolved now.

Reference: [cloud-sdk-docker/issues/497](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/497)

**Pull request closed without merging**
