### PR TITLE
disallow oauth2client v2

### LINKED ISSUE #330: all commands fail with ImportError: No module named gce
```
(py2) [ayush@devbox]$ gsutil ls gs://uspto-pair
Traceback (most recent call last):
  File "/opt/py2/bin/gsutil", line 9, in <module>
    load_entry_point('gsutil==4.16', 'console_scripts', 'gsutil')()
  File "/opt/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/opt/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/opt/py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/gslib/__main__.py", line 53, in <module>
  File "build/bdist.linux-x86_64/egg/gslib/wildcard_iterator.py", line 37, in <module>
  File "build/bdist.linux-x86_64/egg/gslib/translation_helper.py", line 25, in <module>
  File "/opt/py2/lib/python2.7/site-packages/google_apitools-0.4.12-py2.7.egg/apitools/base/py/__init__.py", line 20, in <module>
    from apitools.base.py.base_api import *
  File "/opt/py2/lib/python2.7/site-packages/google_apitools-0.4.12-py2.7.egg/apitools/base/py/base_api.py", line 33, in <module>
    from apitools.base.py import credentials_lib
  File "/opt/py2/lib/python2.7/site-packages/google_apitools-0.4.12-py2.7.egg/apitools/base/py/credentials_lib.py", line 28, in <module>
    import oauth2client.gce
ImportError: No module named gce
```

temp fix: `oauth2client.gce` has moved to `oauth2client.contrib.gce`

### PR DESCRIPTION
**Pull request by scragg0x**
fixes #330

### CODE REVIEW

**Comment by thobrla** [comment]
We'll need to do a PyPi push to fix this, which will require release testing.  So in the meantime I think forcing install of 1.5.2 is the best workaround.

**Comment by scragg0x** [comment]
I signed it!

**Comment by scragg0x** [comment]
@thobrla true, that is what did.  All new installs via pip will be broken in the mean time. :(

**Comment by thobrla** [comment]
Closing this request as we updated this here: https://github.com/GoogleCloudPlatform/gsutil/commit/436ab5424d8c1d8fa3e9a76e1e9beab199a69702

**Pull request closed without merging**
