### PR TITLE
Add -z and -Z options for gzip encoding to rsync command

### PR DESCRIPTION
**Pull request by stanhu**
This enables `rsync` to use the same options used in `cp` to compress
files before uploading.

Closes https://github.com/GoogleCloudPlatform/gsutil/issues/579

### CODE REVIEW

**Comment by stanhu** [comment]
@dilipped Would you mind having a look?

**Comment by dilipped** [comment]
Thanks for the PR! I am a bit busy this week, so I will take a look at this next week.

**Comment by dilipped** [comment]
The -z option compresses the file before uploading, so the size and hash of the file stored at the destination will not be the same as the file at the source, and hence future rsync commands will not be able to correctly identify the diff. For this reason, we should not be supporting the -z and -Z flag in rsync. Please consider using the -j or -J option or using the `cp` command which supports this flag. I am going to close this PR, but feel free to leave comments if you have any questions. Thanks!

**Comment by stanhu** [comment]
@dilipped Thanks for that information. Ah, I see that these compressed files are always overwritten in an `rsync`. That's not such a bad problem for us; we'd rather have the files copied again if necessary as long as they are compressed. I suppose we could just switch to `cp`, but then large files that aren't compressed would then be copied unnecessarily. I wonder if there is a middle ground here?

**Comment by dilipped** [comment]
Rsync is meant to sync the data between two folders, so having the files compressed at one end does not seem like the correct behavior for rsync. Like I said, `gsutil cp` is the right command to achieve something like this, and I am glad you have found the workaround :)

**Pull request closed without merging**
