### PR TITLE
Merge Python 2 / 3 compatibility changes into master branch

### PR DESCRIPTION
**Pull request by catleeball**
This branch contains many compatibility changes to allow Gsutil to run
in both Python 2.7 and Python 3.5+ environments.

Merged master onto `py-six-onto-master` branch with `merge master -X ours`.

Bug: #29

### CODE REVIEW

**Comment by houglum** [comment]
I'm assuming that using `-ours` as the merge strategy means this is pretty much identical to our review in #726.  So if this stuff passes all the tests for 2.7, 3.5-3.7 on all supported OSs, let's merge it. :)

**Comment by catleeball** [comment]
> I'm assuming that using `-ours` as the merge strategy means this is pretty much identical to our review in #726. So if this stuff passes all the tests for 2.7, 3.5-3.7 on all supported OSs, let's merge it. :)

Sounds good to me @houglum !  I've got XML tests running on Mac and Linux currently, JSON came out clean. So far so good. :+1: I did encounter a failure in `test_rm.test_slasher_horror_film` but couldn't reproduce it; it looked like an ephemeral error where an object failed to delete, retried, but before the retry succeeded, the delete bucket operation failed because it wasn't empty.

So `todo` there might be to check that the delete object retry in the `rm` also postpones the delete bucket operation. But I can't make it reproduce the error, so maybe a one-off thing anyways. :)

**Comment by catleeball** [comment]
@houglum Manual tests came back clear, going to merge this. :balloon:

**Comment by psztur** [comment]
any ideas on how far is it from being released?

**Comment by catleeball** [comment]
Hi @psztur ! We're preparing to release v4.39 soon! I'll post an update to bug #29 once the new version is out, and I'll check with my teammate regarding more timeline specifics if we are able to share.

All the changes for compatibility are merged into `master` branch, so if you want to get a head start integrating with the latest, please feel free to clone from the `master` branch of the gsutil repository!

**Pull request merged**
